export const subjects = [
  { id: 1, label: "Mathematics", icon: "📐" },
  { id: 2, label: "Physics", icon: "⚛️" },
  { id: 3, label: "Chemistry", icon: "🧪" },
  { id: 4, label: "Biology", icon: "🧬" },
  { id: 5, label: "English", icon: "📚" },
  { id: 6, label: "History", icon: "🏛️" },
  { id: 7, label: "Computer Science", icon: "💻" },
  { id: 8, label: "Economics", icon: "📊" },
  { id: 9, label: "Languages", icon: "🌍" },
  { id: 10, label: "Test Prep", icon: "✍️" },
];

export const tutors = [
  {
    id: 1,
    name: "Dr. Sarah Chen",
    subject: "Mathematics",
    rating: 4.9,
    ratePerHour: 65,
    bio: "Ex-Google engineer with a PhD in Physics. Specialist in calculus and algebra.",
    avatar: "https://i.pravatar.cc/150?u=sarahchen",
    available: true,
  },
  {
    id: 2,
    name: "James Wilson",
    subject: "Physics",
    rating: 4.8,
    ratePerHour: 55,
    bio: "Passionate about making complex physics concepts simple. 10+ years experience.",
    avatar: "https://i.pravatar.cc/150?u=jameswilson",
    available: true,
  },
  {
    id: 3,
    name: "Elena Rodriguez",
    subject: "Chemistry",
    rating: 4.7,
    ratePerHour: 50,
    bio: "Organic chemistry specialist. I help students visualize molecular structures.",
    avatar: "https://i.pravatar.cc/150?u=elenarodriguez",
    available: true,
  },
  {
    id: 4,
    name: "Prof. Mark Thompson",
    subject: "Biology",
    rating: 4.9,
    ratePerHour: 70,
    bio: "University professor focusing on genetics and molecular biology. Author of 3 textbooks.",
    avatar: "https://i.pravatar.cc/150?u=markthompson",
    available: false,
  },
  {
    id: 5,
    name: "Emily Parker",
    subject: "English",
    rating: 4.8,
    ratePerHour: 45,
    bio: "Literature enthusiast and creative writing coach. Specialist in SAT/ACT English.",
    avatar: "https://i.pravatar.cc/150?u=emilyparker",
    available: true,
  },
  {
    id: 6,
    name: "David Kim",
    subject: "History",
    rating: 4.6,
    ratePerHour: 40,
    bio: "Modern history expert. Making history feel alive through storytelling and analysis.",
    avatar: "https://i.pravatar.cc/150?u=davidkim",
    available: true,
  },
  {
    id: 7,
    name: "Sophie Bennett",
    subject: "Computer Science",
    rating: 4.9,
    ratePerHour: 60,
    bio: "Full-stack developer teaching Python, JS, and Data Structures. Practical approach.",
    avatar: "https://i.pravatar.cc/150?u=sophiebennett",
    available: true,
  },
  {
    id: 8,
    name: "Robert Miller",
    subject: "Economics",
    rating: 4.7,
    ratePerHour: 55,
    bio: "Investment banker turned tutor. Specialize in micro and macro economics for high school.",
    avatar: "https://i.pravatar.cc/150?u=robertmiller",
    available: true,
  },
  {
    id: 9,
    name: "Lucia Garcia",
    subject: "Languages",
    rating: 4.8,
    ratePerHour: 45,
    bio: "Native Spanish speaker and French teacher. Focus on conversational fluency.",
    avatar: "https://i.pravatar.cc/150?u=luciagarcia",
    available: true,
  },
  {
    id: 10,
    name: "Alex Johnson",
    subject: "Test Prep",
    rating: 4.9,
    ratePerHour: 75,
    bio: "Master SAT/GRE tutor. Proven track record of 200+ point improvements.",
    avatar: "https://i.pravatar.cc/150?u=alexjohnson",
    available: true,
  },
  {
    id: 11,
    name: "Maria Rossi",
    subject: "Mathematics",
    rating: 4.7,
    ratePerHour: 50,
    bio: "Statistician with a love for teaching. Specializing in AP Statistics.",
    avatar: "https://i.pravatar.cc/150?u=mariarossi",
    available: true,
  },
  {
    id: 12,
    name: "Olivia Thorne",
    subject: "Chemistry",
    rating: 4.9,
    ratePerHour: 60,
    bio: "Biochemist helping students master complex reactions. Engaging and experimental.",
    avatar: "https://i.pravatar.cc/150?u=oliviathorne",
    available: true,
  },
];

export const testimonials = [
  {
    id: 1,
    quote: "BrightMind completely transformed my approach to Physics. I went from a C to an A in just 3 months!",
    studentName: "Jason M.",
    grade: "12th Grade",
    avatar: "https://i.pravatar.cc/100?u=jasonm",
  },
  {
    id: 2,
    quote: "The tutors are incredibly patient and know how to explain things in ways that finally click.",
    studentName: "Sarah K.",
    grade: "10th Grade",
    avatar: "https://i.pravatar.cc/100?u=sarahk",
  },
  {
    id: 3,
    quote: "I love the flexibility. Booking a session is seamless, and my Computer Science tutor is elite.",
    studentName: "Liam P.",
    grade: "11th Grade",
    avatar: "https://i.pravatar.cc/100?u=liamp",
  },
  {
    id: 4,
    quote: "Finding a high-quality math tutor was hard until I found BrightMind. Sarah is amazing!",
    studentName: "Ava R.",
    grade: "9th Grade",
    avatar: "https://i.pravatar.cc/100?u=avar",
  },
  {
    id: 5,
    quote: "The personalized attention helped me ace my SATs. Highly recommend the Elite plan.",
    studentName: "Noah W.",
    grade: "12th Grade",
    avatar: "https://i.pravatar.cc/100?u=noahw",
  },
  {
    id: 6,
    quote: "Great platform, great tutors. My grades have never been better and I'm actually enjoying History.",
    studentName: "Mia L.",
    grade: "11th Grade",
    avatar: "https://i.pravatar.cc/100?u=mial",
  },
];

export const pricingPlans = [
  {
    name: "Starter",
    price: 29,
    features: ["4 Sessions / Month", "1 Subject", "Email Support", "Standard Tutors"],
    highlight: false,
  },
  {
    name: "Pro",
    price: 59,
    features: ["10 Sessions / Month", "3 Subjects", "Priority Support", "Expert Tutors", "Workshops"],
    highlight: true,
  },
  {
    name: "Elite",
    price: 99,
    features: ["Unlimited Sessions", "All Subjects", "24/7 VIP Support", "Elite Tutors", "Family Account"],
    highlight: false,
  },
];
