export const subjects = [
  { id: 1, label: "Mathematics AA HL", icon: "📐" },
  { id: 2, label: "Mathematics AA SL", icon: "📏" },
  { id: 3, label: "Mathematics AI HL", icon: "💻" },
  { id: 4, label: "Mathematics AI SL", icon: "🧮" },
  { id: 5, label: "Chemistry HL", icon: "🧪" },
  { id: 6, label: "Chemistry SL", icon: "🔬" },
  { id: 7, label: "Physics HL", icon: "⚛️" },
  { id: 8, label: "Physics SL", icon: "🚀" },
  { id: 9, label: "Economics HL", icon: "📈" },
  { id: 10, label: "Economics SL", icon: "📊" },
];

export const tutors = [
  {
    id: 1,
    name: "Dr. Sarah Chen",
    subject: "Mathematics",
    rating: 4.9,
    ratePerHour: 65,
    bio: "Ex-Google engineer with a PhD in Physics. Specialist in calculus and algebra.",
    avatar: "https://i.pravatar.cc/150?u=sarahchen",
    available: true,
  },
  {
    id: 2,
    name: "James Wilson",
    subject: "Physics",
    rating: 4.8,
    ratePerHour: 55,
    bio: "Passionate about making complex physics concepts simple. 10+ years experience.",
    avatar: "https://i.pravatar.cc/150?u=jameswilson",
    available: true,
  },
  {
    id: 3,
    name: "Elena Rodriguez",
    subject: "Chemistry",
    rating: 4.7,
    ratePerHour: 50,
    bio: "Organic chemistry specialist. I help students visualize molecular structures.",
    avatar: "https://i.pravatar.cc/150?u=elenarodriguez",
    available: true,
  },
  {
    id: 4,
    name: "Prof. Mark Thompson",
    subject: "Biology",
    rating: 4.9,
    ratePerHour: 70,
    bio: "University professor focusing on genetics and molecular biology. Author of 3 textbooks.",
    avatar: "https://i.pravatar.cc/150?u=markthompson",
    available: false,
  },
  {
    id: 5,
    name: "Emily Parker",
    subject: "English",
    rating: 4.8,
    ratePerHour: 45,
    bio: "Literature enthusiast and creative writing coach. Specialist in SAT/ACT English.",
    avatar: "https://i.pravatar.cc/150?u=emilyparker",
    available: true,
  },
  {
    id: 6,
    name: "David Kim",
    subject: "History",
    rating: 4.6,
    ratePerHour: 40,
    bio: "Modern history expert. Making history feel alive through storytelling and analysis.",
    avatar: "https://i.pravatar.cc/150?u=davidkim",
    available: true,
  },
  {
    id: 7,
    name: "Sophie Bennett",
    subject: "Computer Science",
    rating: 4.9,
    ratePerHour: 60,
    bio: "Full-stack developer teaching Python, JS, and Data Structures. Practical approach.",
    avatar: "https://i.pravatar.cc/150?u=sophiebennett",
    available: true,
  },
  {
    id: 8,
    name: "Robert Miller",
    subject: "Economics",
    rating: 4.7,
    ratePerHour: 55,
    bio: "Investment banker turned tutor. Specialize in micro and macro economics for high school.",
    avatar: "https://i.pravatar.cc/150?u=robertmiller",
    available: true,
  },
  {
    id: 9,
    name: "Lucia Garcia",
    subject: "Languages",
    rating: 4.8,
    ratePerHour: 45,
    bio: "Native Spanish speaker and French teacher. Focus on conversational fluency.",
    avatar: "https://i.pravatar.cc/150?u=luciagarcia",
    available: true,
  },
  {
    id: 10,
    name: "Alex Johnson",
    subject: "Test Prep",
    rating: 4.9,
    ratePerHour: 75,
    bio: "Master SAT/GRE tutor. Proven track record of 200+ point improvements.",
    avatar: "https://i.pravatar.cc/150?u=alexjohnson",
    available: true,
  },
  {
    id: 11,
    name: "Maria Rossi",
    subject: "Mathematics",
    rating: 4.7,
    ratePerHour: 50,
    bio: "Statistician with a love for teaching. Specializing in AP Statistics.",
    avatar: "https://i.pravatar.cc/150?u=mariarossi",
    available: true,
  },
  {
    id: 12,
    name: "Olivia Thorne",
    subject: "Chemistry",
    rating: 4.9,
    ratePerHour: 60,
    bio: "Biochemist helping students master complex reactions. Engaging and experimental.",
    avatar: "https://i.pravatar.cc/150?u=oliviathorne",
    available: true,
  },
];

export const testimonials = [
  {
    id: 1,
    quote: "My tutor helped me move from a 4 to a 6 in IB Mathematics AA HL. Their insight into exam-style questions completely changed my approach.",
    studentName: "Jason M.",
    grade: "IB Year 2",
    avatar: "https://i.pravatar.cc/100?u=jasonm",
  },
  {
    id: 2,
    quote: "The personalized attention in Economics HL helped me unlock my true potential. The improvement in my confidence is substantial.",
    studentName: "Sarah K.",
    grade: "IB Year 1",
    avatar: "https://i.pravatar.cc/100?u=sarahk",
  },
  {
    id: 3,
    quote: "Physics SL was a nightmare before I started. Understanding the core concepts and practicing past papers with my tutor made all the difference.",
    studentName: "Liam P.",
    grade: "IB Year 2",
    avatar: "https://i.pravatar.cc/100?u=liamp",
  },
  {
    id: 4,
    quote: "Finding a high-quality Chemistry HL tutor was hard until I found this platform. My grades have improved significantly.",
    studentName: "Ava R.",
    grade: "IB Year 1",
    avatar: "https://i.pravatar.cc/100?u=avar",
  },
  {
    id: 5,
    quote: "The regular progress sharing kept my parents in the loop, and the guaranteed improvement wasn't just a promise. I finally achieved my 7 in Math AI SL.",
    studentName: "Noah W.",
    grade: "IB Year 2",
    avatar: "https://i.pravatar.cc/100?u=noahw",
  },
  {
    id: 6,
    quote: "High quality, result driven personalized tutoring. I was struggling with my IA, and my tutor provided exactly the guidance I needed.",
    studentName: "Mia L.",
    grade: "IB Year 2",
    avatar: "https://i.pravatar.cc/100?u=mial",
  },
];

export const pricingPlans = [
  {
    name: "Starter",
    price: 29,
    features: ["4 Sessions / Month", "1 Subject", "Email Support", "Standard Tutors"],
    highlight: false,
  },
  {
    name: "Pro",
    price: 59,
    features: ["10 Sessions / Month", "3 Subjects", "Priority Support", "Expert Tutors", "Workshops"],
    highlight: true,
  },
  {
    name: "Elite",
    price: 99,
    features: ["Unlimited Sessions", "All Subjects", "24/7 VIP Support", "Elite Tutors", "Family Account"],
    highlight: false,
  },
];
